# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{flowtag}
  s.version = "2.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Chris Lee"]
  s.cert_chain = ["/Users/chris/Documents/projects/rubygems/flowtag/../gem-public_cert.pem"]
  s.date = %q{2012-12-20}
  s.description = %q{presents the user with a GUI interface to visualize and explore flows found from a given pcap file}
  s.email = %q{rubygems@chrislee.dhs.org}
  s.executables = ["flowtag", "ftlistflows", "ftpcap2flowdb", "ftprintflow"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    "bin/flowtag",
    "bin/ftlistflows",
    "bin/ftpcap2flowdb",
    "bin/ftprintflow",
    "lib/flowtag.rb",
    "lib/flowtag/flowcanvas.rb",
    "lib/flowtag/flowdb.rb",
    "lib/flowtag/flowtable.rb",
    "lib/flowtag/pcapparser.rb"
  ]
  s.homepage = %q{https://rubygems.org/gems/flowtag}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.signing_key = %q{/Users/chris/Documents/projects/rubygems/flowtag/../gem-private_key.pem}
  s.summary = %q{FlowTag visualizes pcap files for forensic analysis}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<tk-double-slider>, [">= 0.1.0"])
      s.add_runtime_dependency(%q<tk-parallel-coordinates>, [">= 0.1.0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.2.3"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_runtime_dependency(%q<tk-double-slider>, [">= 0.1.0"])
      s.add_runtime_dependency(%q<tk-parallel-coordinates>, [">= 0.1.0"])
    else
      s.add_dependency(%q<tk-double-slider>, [">= 0.1.0"])
      s.add_dependency(%q<tk-parallel-coordinates>, [">= 0.1.0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.2.3"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<tk-double-slider>, [">= 0.1.0"])
      s.add_dependency(%q<tk-parallel-coordinates>, [">= 0.1.0"])
    end
  else
    s.add_dependency(%q<tk-double-slider>, [">= 0.1.0"])
    s.add_dependency(%q<tk-parallel-coordinates>, [">= 0.1.0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.2.3"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<tk-double-slider>, [">= 0.1.0"])
    s.add_dependency(%q<tk-parallel-coordinates>, [">= 0.1.0"])
  end
end

